# Site settings
title: Marvin Min
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Marvin Min
user_description: I'm a MDS student and I was born in 1986":" <a href="https://mauriciourraco.com" target="_blank">https://mauriciourraco.com</a>
user_title: MDS Student (UBC Vancouver)
email: Marvin.cmin@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
